# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.24.1
_src_path: gh:tsvikas/python-template
cli_framework: none
format_tool: black
get_package_version_from_vcs: true
github_user: tsvikas
in_codecov: true
in_pypi: false
in_rtd: false
jupyter_files: forbid
license: Proprietary
package_description: Telegram bot to play Hanabi with your friends.
package_name: hanagram
project_name: hanagram
python_min: 11
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
