# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.14.0
_src_path: gh:tsvikas/python-template
format_tool: black
get_package_version_from_vcs: true
github_user: tsvikas
has_cli: false
jupyter_files: forbid
license: Proprietary
package_description: Telegram bot to play Hanabi with your friends.
package_name: hanagram
project_name: hanagram
python_min: 11
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
